config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  get 'sessions/new'

  get 'works/main'

  post 'works/action'




  get 'admins/main'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #部分テンプレートの部分
  # get 'admins/preprocess'
  # get 'admins/allocation'
  # get 'admins/progress'

  #割り当てしたときのrouting
  post 'admins/create_allocation'


  resources :users
end

app/models/allocation.rb
class Allocation < ApplicationRecord
    validates :user_id, presence: true
    validates :annotation_id, presence: true

    belongs_to :user
    belongs_to :annotation
    # has_many :annotations
end

app/models/annotation.rb
class Annotation < ApplicationRecord
    validates :path, presence: true
    validates :category_id, presence: true
    validates :information, presence: true
    validates :state, presence: true

    belongs_to :allocation

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/picture.rb
# class Picture < ApplicationRecord
#     validates :user_id, presence: true
#     validates :path, presence: true
#     validates :state, presence: true

#     belongs_to :user

#     mount_uploader :path, ImageUploader
# end

app/models/state.rb
class State < ApplicationRecord
      belongs_to :annotaion
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: {message: "%{value}を入力してください"}
  validates :password, presence: {message: "%{value}を入力してください"}
  has_secure_password

  #名前の文字数制限
  validates :name, length: {maximum: 15, message: "は15文字以内にしてください"}

  #パスワードの文字数制限
  validates :password, length: {in: 8..32, too_long:"は32文字以内にしてください", too_short:"は8文字以上にしてください"}
  validates :password, format: {with: /(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)/, message: "%{value}はアルファベット（大小）と半角数字の混合にしてください"}

  #パスワードが一致しているかの確認
  validates :password, confirmation: {message: "とpasswordの値が一致していません"}

  #アソシエーション
  has_many :annotations
  has_many :allocations
  has_many :allocation_annotations, through: :allocations, source: 'annotation'

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def main

    #ユーザー一覧を取得
    users = User.all
    names = []
    for user in users
      content = {id: user.id, name: user.name}
      names.push(content)
    end
    @users = names

    #アノテーション画像の一覧を取得
    annotation = Annotation.all
    annotation = annotation.select{|i| i.state == 1 }
    @contents = []
    for anno in annotation
      information = anno["information"].split(",")
      content = [anno["id"],anno["path"],information]
      @contents.push(content)
    end

    #割り当てられた作業を表示
    #ユーザーをすべて取得
    users = User.all

    @progress=[]
    for user in users

      #ユーザーに紐付いたannotationsを取得
      allos = user.allocation_annotations
      #annotationの数量
      total = allos.count

      if total == 0
        next
      end

      end_all = allos.select{|i| i.state == 3 }.count
      content = [user.name, ((end_all.to_f / total.to_f)*100).ceil]
      @progress.push(content)
    end

  end

  #前処理の部分テンプレート
  # def preproccess
  # end
  def create_allocation

    #allocationテーブルに保存する
    userId = params["allocation"]["user"]
    pictureId = params["allocation"]["pictures"]

    for pic in pictureId
      allocation = Allocation.new
      allocation.user_id = userId
      allocation.annotation_id = pic
      allocation.save

      anno = Annotation.find(pic)
      #2:作業中に変更する
      anno.update_attribute(:state, 2)
    end

    redirect_to admins_main_path

  end

  #割り当て
  # def allocation
  # end

  #進捗の部分テンプレート
  # def progress
  # end

  # private
  # def allocation_params
  #   params.require(:allocation).permit(:user,:pictures)
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: name_params[:name])
    if user && user.authenticate(password_params[:password])
      log_in user
      redirect_to works_main_path, success: 'ログインしました'
    else
      flash.now[:danger]='ログインに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def name_params
    params.require(:session).permit(:name)
  end

  def password_params
    params.require(:session).permit(:password)
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # binding.pry
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger]='登録に失敗しました'
      render :new
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  # include gon

  def main
    # @user_name = current_user.name

    @user_state=[]
    #アノテーション画像を取得する
    allos = current_user.allocation_annotations

    #selectでstate==2(作業中)のものを選別する
    user_state = allos.select{|i| i.state == 2 }

    #working状態の画像の数を取得
    @count = user_state.count

    #userの情報を配列に入れる(@countが0のときはerrorになるかもしれないので除外)
    if @count != 0
        @user_state = [user_state[0].id, user_state[0].path, user_state[0].information]
    end

    #進捗率を計算する
    total = allos.count
    if total == 0
      #ユーザー名と、進捗率を入れる
      @progress = [current_user.name, 0]
    else
      end_all = allos.select{|i| i.state == 3 }.count
      @progress = [current_user.name, ((end_all.to_f / total.to_f)*100).ceil]
    end
  end

  def action

    anno = Annotation.find(params["img_id"].to_i)
    categoryId = params["judege"].to_i

    #cateogryidに応じた文字列を取得
    if categoryId == 1
      categoryStr = 'b'
    elsif categoryId == 2
      categoryStr = 'n'
    else
      categoryStr = 'u'
    end

    newInfo = params["info"][0..-2]+categoryStr

    # アノテーションの状態を終了(state: 3)に変更する
    anno.update_attribute(:state, 3)
    #カテゴリーの種類を変更する
    anno.update_attribute(:category_id, params["judege"].to_i)
    #情報を更新する
    anno.update_attribute(:information, newInfo)

    redirect_to works_main_path

  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def current_user
  #   @current_user ||= User.find_by(id: session[:user_id])
  # end

  # def logged_in?
  #   !current_user.nil?
  # end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admins/_allocation.html.erb
<%= form_for :allocation , url: admins_create_allocation_path do |f| %>
<div class="row mt-3">
  <div class="col-10 offset-1">
    <div class="form-group">
      <label for="select1a">ユーザー選択:</label>
      <%= f.select :user, options_for_select(users.map{|c|[c[:name], c[:id]]}), {}, {class: 'form-control', id: 'select1a'} %>
    </div>
  </div>
</div>
<div class="row mt-3">
  <div class="col-10 offset-1">
    <p>画像選択:</p>

<!--     <p>*必ず終了よりも開始の方が小さくなるように設定してください</p>
    <div class="row mb-3">
      <div class="col-3">
        <label>開始:</label>
        <%#= f.number_field :start %>
      </div>
      <div class="col-3 offset-1">
        <label>終了:</label>
        <%#= f.number_field :end %>
      </div>
    </div> -->

    <table class="table table-striped">
      <tr class="thead-dark">
        <th></th>
        <th>画像ID</th>
        <th>画像</th>
        <th>情報</th>
      </tr>
      <% contents.each_with_index do |content, i| %>
      <%# contents.each do |content| %>
        <tr>
          <td>
            <%#= i+1 %>
            <%#= f.check_box 'pictures[content][]', content,false,id:"samurai_ingredients_#{i}"%>
            <%= f.check_box :pictures, {multiple: true}, content[0] ,nil%>

          </td>
          <%#= image_tag content[0], class: "navbar-brand" %>
          <td><%= content[0] %></td>
          <td><%= content[1] %></td>
          <td><%= content[2] %></td>
        </tr>
      <% end %>

    </table>
  </div>
</div>
<div class="row mt-3">
  <div class="col-2 offset-5">
      <%= f.submit "割り当て",class: "btn btn-primary btn-block"%>
  </div>
</div>
<% end %>

app/views/admins/_preprocess.html.erb
<!-- <p>ここは前処理</p> -->

app/views/admins/_progress.html.erb
<% progress.each do |pro| %>

  <div class=" col-10 offset-1 card mt-3">
      <p class="mt-3">作業者ID : <%= pro[0] %></p>
      <div class="progress mb-3" style="height: 40px;">
        <div class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width:<%= pro[1]%>%;"><%= pro[1]%>%</div>
      </div>
  </div>

<% end %>

app/views/admins/allocation.js.erb
// $("#allocation").html("<%= j(render 'allocation') %>");
// var tab =  $("#allocation-tab");
// $("#allocation").css('display', 'block');
// $("#preprocess").css('display', 'none');
// $("#progress").css('display', 'none');

app/views/admins/main.html.erb
<!-- タブ・メニュー -->
<div class="mt-3">
  <ul class="nav nav-tabs">
<!--     <li class="nav-item">
      <a class="nav-link active" href="#sampleContentA" data-toggle="tab">前処理</a>
    </li> -->
    <li class="nav-item">
      <a class="nav-link active" href="#sampleContentB" data-toggle="tab">割り当て</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#sampleContentC" data-toggle="tab">作業進捗</a>
    </li>
  </ul>
</div>

<!-- タブ内容 -->

<div class="tab-content">
   <!-- <div class="tab-pane" id="sampleContentA"> -->
      <%#= render partial: "preprocess" %>
   <!-- </div> -->
   <div class="tab-pane active" id="sampleContentB">
      <%= render partial: "allocation",locals: { users: @users , contents: @contents}%>
   </div>
   <div class="tab-pane" id="sampleContentC">
      <%= render partial: "progress", locals: {progress: @progress} %>
      <%#= render partial: "progress",locals: { users: @users , contents: @contents}%>
   </div>
</div>

<!-- <ul class="nav nav-tabs mt-3">
  <li class="nav-item"> -->
    <%#= link_to "前処理", admins_preprocess_path, class: "nav-link active", id: "preprocess-tab", remote: true %>
<!--   </li>
  <li class="nav-item"> -->
    <%#= link_to "割り当て", admins_allocation_path, class: "nav-link", id: "allcation-tab", remote: true %>
<!--   </li>
  <li class="nav-item"> -->
    <%#= link_to "進捗", admins_progress_path, class: "nav-link", id: "progress-tab", remote: true %>
<!--   </li>
</ul> -->

<!-- mypagesの部分テンプレート -->
<!-- <div id="preprocess"></div>

<div id="allocation"></div>

<div id="progress"></div> -->

app/views/admins/preprocess.js.erb
// $("#preprocess").html("<%= j(render 'preprocess') %>");
// var tab =  $("#preprocess-tab");
// $("#allocation").css('display', 'none');
// $("#preprocess").css('display', 'block');
// $("#progress").css('display', 'none');

app/views/admins/progress.js.erb
// $("#progress").html("<%= j(render 'progress') %>");
// var tab =  $("#progress-tab");
// $("#allocation").css('display', 'none');
// $("#preprocess").css('display', 'none');
// $("#progress").css('display', 'block');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BirdAnnotation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
        <div class="navbar navbar-default bg-primary">
            <% if logged_in? %>
                <p class="text-white">（仮）野鳥アノテーションシステム</p>

                <%= link_to("管理者用", admins_main_path, {class: "nav-item nav-link text-white "}) %>
                <%#= link_to("マイページ", works_main_path, {class: "nav-item nav-link text-white active"}) %>
                <%= link_to works_main_path do %>
                    <span>
                        <p class="h5 text-white d-inline"><%= current_user.name %></p>
                        <i class="far fa-user fa-2x text-white d-inline"></i>
                    </span>
                <% end %>

                <%= link_to logout_path,method: :delete do %>
                    <spna><i class="fas fa-sign-out-alt fa-2x text-white"></i></spna>
                <% end %>
                <%#= link_to("ログアウト", logout_path, { method: :delete, class: "nav-item nav-link text-white"}) %>
            <% else %>
                <p class="text-white">（仮）野鳥アノテーションシステム</p>
                <%#= link_to("新規登録", new_user_path, {class: "nav-item nav-link text-white"}) %>
                <%#= link_to("ログイン", login_path, {class: "nav-item nav-link text-white"}) %>
            <% end %>
        </div>
    <%= yield %>
    </div>
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      })
    </script>
  </body>
</html>

app/views/users/new.html.erb
<div class="row">
  <div class="offset-4 col-4 mt-3">
    <%= form_for @user do |f| %>
      <!-- 名前の入力フォーム -->
      <div class="form-group">
        <%= f.label :name, class: "text-primary" %>
        <%= f.text_field :name, class: "form-control"%>
        <!-- エラーメッセージ -->
        <% if @user.errors.any? %>
          <% @user.errors.full_messages_for(:name).each do |message| %>
            <p class="text-white"><%= message %></p>
          <% end %>
        <% end %>
      </div>
      <!-- パスワードの入力フォーム -->
      <div class="form-group">
        <%= f.label :password, class: "text-primary"%>
        <%= f.text_field :password, class: "form-control" %>
        <!-- エラーメッセージ -->
        <% if @user.errors.any? %>
          <% @user.errors.full_messages_for(:password).each do |message| %>
            <p class="text-primary"><%= message %></p>
          <% end %>
        <% end %>
      </div>
      <!-- パスワードの確認フォーム -->
      <div class="form-group">
        <%= f.label :password_confirmation, class: "text-primary"%>
        <%= f.text_field :password_confirmation, class: "form-control" %>
        <!-- エラーメッセージ -->
        <% if @user.errors.any? %>
          <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
            <p class="text-primary"><%= message %></p>
          <% end %>
        <% end %>
      </div>
      <div class="row">
         <div class="col-4 offset-4">
            <%= f.submit "登録", class: "btn btn-block btn-primary"%>
         </div>
      </div>
      <div class="row">
          <div class="col-6 offset-3 mx-auto">
            <a class="text-primary" href="/">ログインに戻る</a>
          </div>
      </div>
    <% end %>
  </div>
</div>